//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapa_Curricular
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Estudiantes_UABCEntities : DbContext
    {
        public Estudiantes_UABCEntities()
            : base("name=Estudiantes_UABCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstadoMateria> EstadoMateria { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Expedientes> Expedientes { get; set; }
        public virtual DbSet<Mapa_Curricular> Mapa_Curricular { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Programa_Educativo> Programa_Educativo { get; set; }
        public virtual DbSet<Trayectorias_academicas> Trayectorias_academicas { get; set; }
        public virtual DbSet<Tutores> Tutores { get; set; }
    }
}
