//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapa_Curricular
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trayectorias_academicas
    {
        public int ID { get; set; }
        public System.DateTime Fecha_ingreso { get; set; }
        public int ExpedienteID { get; set; }
        public int MateriaClave { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public int EstadoID { get; set; }
        public bool Seleccion { get; set; }
    
        public virtual EstadoMateria EstadoMateria { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
